
### get the second deck
GET http://localhost:8080/v1/deck/2
Authorization: Bearer {{auth_token}}
Accept: application/json

### get a deck which doesn't exist (404)
GET http://localhost:8080/v1/deck/999999999999
Authorization: Bearer {{auth_token}}
Accept: application/json

### Save a new deck
POST http://localhost:8080/v1/deck
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Mon 2eme deck",
  "secret": true,
  "description": "Créé par HTTP POST !",
  "cards": [
    {
      "pk": {
        "card": {
          "id": 1
        }
      },
      "nbCard": 1
    },
    {
      "pk": {
        "card": {
          "id": 2
        }
      },
      "nbCard": 3
    }
  ]
}

### update the new deck (id known)
POST http://localhost:8080/v1/deck
Content-Type: application/json

{
  "id": 2,
  "name": "Mon 2eme deck",
  "secret": true,
  "description": "Créé par HTTP POST !",
  "cards": [
    {
      "pk": {
        "card": {
          "id": 1
        }
      },
      "nbCard": 1
    },
    {
      "pk": {
        "card": {
          "id": 2
        }
      },
      "nbCard": 1
    }
  ]
}